"""Standing invariant check for the genealogy. Run before and after any change.

This exists because on 2026-07-30 a duplicate merge silently ADDED cycles (52 -> 54) and
nothing caught it until the extracts were regenerated by hand and the numbers compared.
Every check up to that point was bespoke and written after the fact. This is the standing
one.

    python wiki-scripts/check_invariants.py                 # check, print, exit 1 on regression
    python wiki-scripts/check_invariants.py --baseline      # record current state as the baseline
    python wiki-scripts/check_invariants.py --source items  # read item JSONs instead of edges.tsv

Invariants:
  I1  no record is its own ancestor            (cycle count must not INCREASE)
  I2  no record is its own parent              (self-loops must be zero, always)
  I3  every edge endpoint has a persons.tsv row (dangling endpoints must not increase)
  I4  children with >2 parents must not increase

Baseline lives in wikibase/analysis/invariants.json and is committed, so a regression is
visible in review as a changed number rather than only at runtime.
"""

import collections
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
A = ROOT / "wikibase" / "analysis"
BASELINE = A / "invariants.json"


def load_edges_from_tsv():
    par = collections.defaultdict(set)
    child = collections.defaultdict(set)
    with open(A / "edges.tsv", encoding="utf-8") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            par[r["child"]].add(r["parent"])
            child[r["parent"]].add(r["child"])
    return par, child


def load_edges_from_items():
    """Source of truth. Slower (~10 min) but immune to a stale extract."""
    par = collections.defaultdict(set)
    child = collections.defaultdict(set)
    import os
    with os.scandir(A.parent / "items") as it:
        for e in it:
            if not e.name.endswith(".json"):
                continue
            try:
                with open(e.path, "rb") as fh:
                    d = json.loads(fh.read())
            except Exception:
                continue
            if not isinstance(d, dict):
                continue
            q = d.get("id") or e.name[:-5]
            claims = d.get("claims") or {}
            for c in claims.get("P20", ()):
                v = ((c.get("mainsnak") or {}).get("datavalue") or {}).get("value")
                if isinstance(v, dict) and v.get("id"):
                    par[v["id"]].add(q)
                    child[q].add(v["id"])
            for pid in ("P47", "P48"):
                for c in claims.get(pid, ()):
                    v = ((c.get("mainsnak") or {}).get("datavalue") or {}).get("value")
                    if isinstance(v, dict) and v.get("id"):
                        par[q].add(v["id"])
                        child[v["id"]].add(q)
    return par, child


def count_cycles(par):
    """Number of strongly connected components of size >1, plus self-loops.
    An SCC of size >1 in a parent graph means everyone in it is their own ancestor.
    Tarjan, iterative -- the graph is ~129k edges and recursion would blow the stack."""
    index, low, on_stack, stack, idx = {}, {}, set(), [], [0]
    sccs = []
    nodes = set(par) | {p for ps in par.values() for p in ps}
    for root in nodes:
        if root in index:
            continue
        work = [(root, iter(par.get(root, ())))]
        index[root] = low[root] = idx[0]
        idx[0] += 1
        stack.append(root)
        on_stack.add(root)
        while work:
            node, it = work[-1]
            advanced = False
            for nxt in it:
                if nxt not in index:
                    index[nxt] = low[nxt] = idx[0]
                    idx[0] += 1
                    stack.append(nxt)
                    on_stack.add(nxt)
                    work.append((nxt, iter(par.get(nxt, ()))))
                    advanced = True
                    break
                if nxt in on_stack:
                    low[node] = min(low[node], index[nxt])
            if advanced:
                continue
            work.pop()
            if work:
                low[work[-1][0]] = min(low[work[-1][0]], low[node])
            if low[node] == index[node]:
                comp = []
                while True:
                    w = stack.pop()
                    on_stack.discard(w)
                    comp.append(w)
                    if w == node:
                        break
                if len(comp) > 1:
                    sccs.append(comp)
    return sccs


def measure(source):
    par, child = load_edges_from_items() if source == "items" else load_edges_from_tsv()
    sccs = count_cycles(par)
    self_loops = sorted(q for q, ps in par.items() if q in ps)
    persons = set()
    with open(A / "persons.tsv", encoding="utf-8") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            persons.add(r["qid"])
    endpoints = set(par) | {p for ps in par.values() for p in ps}
    dangling = sorted(endpoints - persons)
    multi = sum(1 for q, ps in par.items() if len(ps) > 2)
    return {
        "source": source,
        "tangled_components": len(sccs),
        "records_in_a_cycle": sum(len(c) for c in sccs),
        "largest_component": max((len(c) for c in sccs), default=0),
        "self_loops": len(self_loops),
        "dangling_endpoints": len(dangling),
        "children_over_2_parents": multi,
        "_self_loop_examples": self_loops[:10],
        "_dangling_examples": dangling[:10],
    }


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    source = "items" if "--source" in sys.argv and "items" in sys.argv else "tsv"
    cur = measure(source)

    print(f"source: {cur['source']}")
    for k in ("tangled_components", "records_in_a_cycle", "largest_component",
              "self_loops", "dangling_endpoints", "children_over_2_parents"):
        print(f"  {k:26s} {cur[k]}")
    if cur["_self_loop_examples"]:
        print(f"  self-loop examples: {cur['_self_loop_examples']}")

    if "--baseline" in sys.argv:
        BASELINE.write_text(json.dumps(cur, indent=2) + "\n", encoding="utf-8")
        print(f"\nbaseline written -> {BASELINE}")
        return 0

    if not BASELINE.exists():
        print("\nno baseline yet; run with --baseline to record one")
        return 0

    base = json.loads(BASELINE.read_text(encoding="utf-8"))
    fails = []
    if cur["self_loops"] > 0:
        fails.append(f"I2 self-loops present: {cur['self_loops']} (must always be 0)")
    for key, label in (("tangled_components", "I1 cycles"),
                       ("dangling_endpoints", "I3 dangling endpoints"),
                       ("children_over_2_parents", "I4 multi-parent children")):
        if cur[key] > base.get(key, 0):
            fails.append(f"{label} INCREASED: {base.get(key)} -> {cur[key]}")

    print()
    if fails:
        for f in fails:
            print("FAIL:", f)
        return 1
    improved = [k for k in ("tangled_components", "dangling_endpoints", "children_over_2_parents")
                if cur[k] < base.get(k, 0)]
    print("PASS -- no invariant regressed"
          + (f"; improved: {', '.join(improved)}" if improved else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
